name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Frontend build, test, and deploy
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies (Frontend)
        run: cd frontend && npm install
      - name: Run tests (Frontend)
        run: cd frontend && npm test

  # Backend build, test, and deploy
  backend:
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies (Backend)
        run: cd backend && npm install
      - name: Run tests (Backend)
        run: cd backend && npm test
      - name: Deploy (Backend)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PREM_028 }}
          HOST: ${{ secrets.PREM_028 }}
          USER: ${{ secrets.PREM_028 }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PREM_028 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PREM_028 }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.PREM_028 }}@${{ secrets.PREM_028 }} "cd /path/to/backend && git pull && npm install && pm2 restart app"
